# Generated by Django 2.2.7 on 2019-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('template', models.CharField(default='pages/home.html', max_length=500, verbose_name='Шаблон')),
                ('registration_required', models.BooleanField(default=False, help_text='Если флажок установлен, только зарегистрированные пользователи могут просматривать страницу.', verbose_name='Требуется регистрация')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'unique_together': {('slug',)},
            },
        ),
    ]
