# Generated by Django 2.2.7 on 2019-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='url'),
        ),
    ]
