# Generated by Django 2.2.7 on 2019-11-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='blog.Tag', verbose_name='Тег'),
        ),
    ]
