# Generated by Django 2.2.7 on 2019-12-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191124_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['sort', '-published_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='Статья'),
        ),
    ]
